apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      name: connection
      targetPort: 8086
      protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-persistent-storage
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      name: influxdb-pod
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb-container
          image: influxdb-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influxdb-data
              mountPath: /var/lib/influxdb
            - name: influxdb-configuration
              subPath: influxdb.conf
              mountPath: /etc/influxdb/influxdb.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secret
          livenessProbe:
            initialDelaySeconds: 6
            periodSeconds: 6
            timeoutSeconds: 5
            httpGet:
              path: /ping
              port: 8086
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-persistent-storage
        - name: influxdb-configuration
          configMap:
            name: influxdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-address = "127.0.0.1:8088"
    ### [meta]
    ### Controls the parameters for the Raft consensus group that stores metadata
    ### about the InfluxDB cluster.

    [meta]
      dir = "/var/lib/influxdb/meta"
    
    ### [data]
    ### Controls where the actual shard data for InfluxDB lives and how it is
    ### flushed from the WAL. "dir" may need to be changed to a suitable place
    ### for your system, but the WAL settings are an advanced configuration. The
    ### defaults should work for most systems.

    [data]
      dir = "/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"

    ###
    ### [http]
    ###
    ### Controls how the HTTP endpoints are configured. These are the primary
    ### mechanism for getting data into and out of InfluxDB.
    ###

    [http]
      enabled = true
      auth-enabled = false
      bind-address = ":8086"


    ###
    ### [[graphite]]
    ###
    ### Controls one or many listeners for Graphite data.
    ###

    [[graphite]]
      enabled = false
      database = "telegraf"
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: influxdb
  name: influxdb-secret
type: Opaque
stringData:
  INFLUXDB_CONFIG_PATH: /etc/influxdb/influxdb.conf
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: admin
  INFLUXDB_DB: telegraf
  INFLUXDB_USER: user
  INFLUXDB_USER_PASSWORD: user