apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 20
    name: data
    targetPort: 20
    protocol: TCP
  - port: 21
    name: connection
    targetPort: 21
    protocol: TCP
  - port: 21100
    name: passive-port
    targetPort: 21100
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps-container
        image: ftps-image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21100
        volumeMounts:
         - name: ftps-configuration
           subPath: vsftpd.conf
           mountPath: /etc/vsftpd/vsftpd.conf
           readOnly: true
      volumes:
        - name: ftps-configuration
          configMap:
            name: ftps-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ftps
  name: ftps-config
data:
  vsftpd.conf: |
    #common
    listen=YES
    max_clients=100
    max_per_ip=30
    idle_session_timeout=600
    data_connection_timeout=120
    seccomp_sandbox=NO
    ftpd_banner=Welcome to FTP service.
    dirmessage_enable=YES
    hide_ids=YES
    connect_from_port_20=YES
    port_enable=YES
    pasv_enable=YES
    pasv_address=192.168.99.101
    pasv_min_port=21100
    pasv_max_port=21100
    #
    #vsftpd commands
    write_enable=YES
    allow_writeable_chroot=YES
    #
    #upload/download
    ascii_upload_enable=YES
    ascii_download_enable=YES
    #
    #ANON REQUESTS DISABLED
    anonymous_enable=NO
    #
    #Rules for users
    local_enable=YES
    chroot_local_user=YES
    chroot_list_enable=NO
    local_umask=022
    #
    #SSL
    ssl_enable=YES
    ssl_tlsv1=YES
    ssl_sslv2=NO
    ssl_sslv3=NO
    rsa_cert_file=/etc/ssl/certs/vsftpd.pem
    rsa_private_key_file=/etc/ssl/private/vsftpd.key
    #
    #Journaling
    xferlog_enable=YES
    xferlog_file=/var/log/vsftpd.log
    xferlog_std_format=YES